### ISSUE TITLE
_pages/subsurface-mobile.en

### ISSUE THREAD

**Issue by salvadorcunat** [Subsurface-divelog/Subsurface-website#66]
Dirk, when you recover from the jetlag, could you copy
_pages/subsurface-mobile.en to _pages/subsurface-mobile.es and sync, so
I can translate this interesting page?

Interesting and, hopefully, getting more interesting next days :-)

Best regards.

**Comment by mturkia** [comment]
You can do that yourself. Once you have the new file ready to be added, run

git add _pages/subsurface-mobile.es
git commit -s

**Comment by dirkhh** [comment]
Sorry., I somehow missed that one. @salvadorcunat  was correct, if they get added in git then the references go all wrong and bad things happen. I'll add them right now.
