### ISSUE TITLE
Spanish translated web weirdnesses

### ISSUE THREAD

**Issue by salvadorcunat** [Subsurface-divelog/Subsurface-website#75]
Good evening.  
A little list:
1.--  about.es doesn't exist in github repo although the web site is updated to 4.6.4 (so I can't change the link to spanish 4.7.1 announcement).
2.-  Also there isn't news.es although there is definitely  a  "Noticias" link in the main page.
3.-  spanish 4.7.1 announcement doesn't seems to be synced from github to wp
4.-  subsurface-mobile.en (and .es, of course) need to be updated to reflect, at least, v2.0 downloading capabilities.
5.-  We have the mobile-manual translated in master, but it is not on web.
6.- I'm probably missing some more  ;-)

1 and 2 (and probably 5) can't be solved via github's PRs  so I think I'll need my wp user reseted.
For 3 forcing a sync, as with german announcement ...
For 4, I can modify, if you want, subsurface-mobile en & es pages via PR, so you can review them before publishing.

Regards

**Comment by Subsurface-divelog** [comment]
> On Oct 24, 2017, at 7:46 PM, salvadorcunat <notifications@github.com> wrote:
> 
> Good evening.
> A little list:
> 1.-- about.es doesn't exist in github repo although the web site is updated to 4.6.4 (so I can't change the link to spanish 4.7.1 announcement).
> 
Something is going wrong with SOME website updates via git.
But I'll admit that I can't parse that statement here. What do you mean by "the web site is updated to 4.6.4"?
> 2.- Also there isn't news.es although there is definitely a "Noticias" link in the main page.
> 
https://subsurface-divelog.org/es/category/noticias/ <https://subsurface-divelog.org/es/category/noticias/>3.- spanish 4.7.1 announcement doesn't seems to be synced from github to wp
> 
see above, I'll fix that manually in a moment.
> 4.- subsurface-mobile.en (and .es, of course) need to be updated to reflect, at least, v2.0 downloading capabilities.
> 
true
> 5.- We have the mobile-manual translated in master, but it is not on web.
> 
I thought I had that pushed. More things going wrong :-(
> 6.- I'm probably missing some more ;-)
> 
> 1 and 2 (and probably 5) can't be solved via github's PRs so I think I'll need my wp user reseted.
> For 3 forcing a sync, as with german announcement ...
> For 4, I can modify, if you want, subsurface-mobile en & es pages via PR, so you can review them before publishing.
> 


I'd love a PR for the subsurface-mobile update. I'll work on 3. I need more information about 1&2

/D

**Comment by salvadorcunat** [comment]
I'm bad explaining myself, less say in a non native language  :-) 

> But I'll admit that I can't parse that statement here. What do you mean by "the web site is updated to 4.6.4"?

I meant, web site is correctly displaying in spanish as 4.6.4. The weird thing is that there is no about.es in github.

> 5.-We have the mobile-manual translated in master, but it is not on web.
I thought I had that pushed. More things going wrong :-(

No,  mobile-manual_es.txt is correctly pushed to git master. I meant, the converted .html file is not applied in web site, and don't know if just applying the .html generated file over the old subsurface-mobile-user-manual.es will work as Jan changed the link to the v2.0 english version  (all this thinking in work via github's PRs, not from WP).

> I'd love a PR for the subsurface-mobile update. 

I won't change too much, just the downloading feature.  It'll be ready in some minutes.

Salva.

**Comment by dirkhh** [comment]
I have no idea why there isn't an about.es. It disappeared in a completely unrelated change. I'll add it manually again and see what happens. As I said earlier - something is going wrong with the git-WP sync these days :-(

I have added a Spanish version of the Subsurface-mobile v2 user manual. Please check that this worked.

**Comment by salvadorcunat** [comment]
I've just pulled your changes and will take a look after dinner. BTW, have sent a PR with changes to the subsurface-mobile pages.
Regards.
Salva.

**Comment by salvadorcunat** [comment]
Pages looks fine for me. I've sent a PR to fix some broken links (including about.en).
The spanish mobile-manual is readable but ... hmmm ... too "text-ish", it's not really formated like the english one.
Regards.
Salva.

**Comment by dirkhh** [comment]
The conversion tool that I use couldn't process the Spanish mobile manual. So I posted the unconverted version as I was to tired to investigate :-(

**Comment by dirkhh** [comment]
OK, I did the conversion by hand... can you check if it now looks better for you?

**Comment by salvadorcunat** [comment]
It looks much better now Dirk. Thanks.
Gonna close the issue.
