### ISSUE TITLE
Links to Subsurface-4.7.4-x86_64.AppImage are broken

### ISSUE THREAD

**Issue by probonopd** [Subsurface-divelog/Subsurface-website#82]
[These links](
https://github.com/Subsurface-divelog/Subsurface-website/search?utf8=%E2%9C%93&q=https%3A%2F%2Fsubsurface-divelog.org%2Fdownloads%2FSubsurface-4.7.4-x86_64.AppImage&type=) are currently broken. Is the plan to host the AppImage on subsurface-divelog.org or simply to link to GitHub Releases where the AppImage currently resides?

On IRC it was discussed that one could have version numbers in released versions instead of SHAs - this line would need to be changed:

https://github.com/Subsurface-divelog/subsurface/blob/fd2e24d145500a70c6612a612b3397ee1898900b/scripts/linux/travisbuild.sh#L41

to "if tagged release, then use the tag; else, use the sha"

**Comment by dirkhh** [comment]
The 'these links' above didn't really work for me. Not sure which links you mean.
By context I assume the AppImages - and indeed, my little script that copied the AppImage to its usual place got the renaming wrong.
I manually fixed it for this release. And I'm working on improving the naming for the AppImages in the continuous build.
Thanks for pointing this out! I'm kinda surprised that no one else stumbled across this, yet...
